import { Product, Collection, Cart } from './types';

export const MOCK_COLLECTIONS: Collection[] = [
  {
    id: 'col-oversized',
    handle: 'oversized-tees',
    title: 'Oversized Tees',
    description: 'Heavyweight 240+ GSM drop-shoulder streetwear tees crafted for ultimate drape and comfort.',
    seo: { title: 'Oversized Streetwear Tees | SNITCH', description: 'Heavyweight acid-wash and graphic oversized t-shirts.' },
    updatedAt: new Date().toISOString(),
    path: '/collections/oversized-tees',
    image: {
      url: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1200&auto=format&fit=crop',
      altText: 'Oversized Streetwear Tees',
      width: 1200,
      height: 800,
    },
  },
  {
    id: 'col-shirts',
    handle: 'korean-fit-shirts',
    title: 'Korean Fit & Cuban Shirts',
    description: 'Breezy Cuban camp collars, satin party shirts, and structured Korean-fit boxy button-downs.',
    seo: { title: 'Korean Fit & Cuban Shirts | SNITCH', description: 'Trendsetting Cuban collar and satin streetwear shirts.' },
    updatedAt: new Date().toISOString(),
    path: '/collections/korean-fit-shirts',
    image: {
      url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1200&auto=format&fit=crop',
      altText: 'Korean Fit Shirts',
      width: 1200,
      height: 800,
    },
  },
  {
    id: 'col-cargos',
    handle: 'parachute-cargos',
    title: 'Parachute & Utility Cargos',
    description: 'Multi-pocket tactical cargos with adjustable ankle drawstrings and wide baggy profiles.',
    seo: { title: 'Parachute & Utility Cargos | SNITCH', description: 'Baggy utility cargos and parachute pants.' },
    updatedAt: new Date().toISOString(),
    path: '/collections/parachute-cargos',
    image: {
      url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1200&auto=format&fit=crop',
      altText: 'Parachute & Utility Cargos',
      width: 1200,
      height: 800,
    },
  },
  {
    id: 'col-coords',
    handle: 'matching-coords',
    title: 'Co-Ord Sets',
    description: 'Effortless luxury matching sets designed for summer resort vibes and urban streetwear.',
    seo: { title: 'Matching Co-Ord Sets | SNITCH', description: 'Men matching streetwear and resort co-ord sets.' },
    updatedAt: new Date().toISOString(),
    path: '/collections/matching-coords',
    image: {
      url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1200&auto=format&fit=crop',
      altText: 'Co-Ord Sets',
      width: 1200,
      height: 800,
    },
  },
  {
    id: 'col-jackets',
    handle: 'varsity-jackets',
    title: 'Varsity & Denim Jackets',
    description: 'Statement varsity bomber jackets, washed vintage denim, and technical utility layers.',
    seo: { title: 'Varsity & Denim Jackets | SNITCH', description: 'Streetwear outerwear and bomber jackets.' },
    updatedAt: new Date().toISOString(),
    path: '/collections/varsity-jackets',
    image: {
      url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1200&auto=format&fit=crop',
      altText: 'Varsity & Denim Jackets',
      width: 1200,
      height: 800,
    },
  },
  {
    id: 'col-footwear',
    handle: 'urban-footwear',
    title: 'Chunky Sneakers & Kicks',
    description: 'Architectural retro runners, high-top platform kicks, and minimalist leather slides.',
    seo: { title: 'Chunky Sneakers | SNITCH', description: 'Urban streetwear sneakers and shoes.' },
    updatedAt: new Date().toISOString(),
    path: '/collections/urban-footwear',
    image: {
      url: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1200&auto=format&fit=crop',
      altText: 'Chunky Sneakers & Kicks',
      width: 1200,
      height: 800,
    },
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-snitch-1',
    handle: 'cyber-tokio-acid-wash-tee',
    availableForSale: true,
    title: 'Cyber Tokio Acid-Wash Oversized Tee',
    description: 'Raw vintage acid-wash drop-shoulder graphic tee crafted from 280 GSM premium organic cotton. High-density puff print detailing on front and back.',
    descriptionHtml: '<p>Raw vintage acid-wash drop-shoulder graphic tee crafted from 280 GSM premium organic cotton. High-density puff print detailing on front and back.</p>',
    options: [
      { id: 'opt-size-1', name: 'Size', values: ['S', 'M', 'L', 'XL', 'XXL'] },
      { id: 'opt-color-1', name: 'Color', values: ['Washed Charcoal', 'Vintage Moss', 'Phantom Black'] },
    ],
    priceRange: {
      minVariantPrice: { amount: '34.00', currencyCode: 'USD' },
      maxVariantPrice: { amount: '34.00', currencyCode: 'USD' },
    },
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1000&auto=format&fit=crop',
      altText: 'Cyber Tokio Acid-Wash Oversized Tee',
      width: 1000,
      height: 1000,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1000&auto=format&fit=crop',
        altText: 'Front View',
      },
      {
        url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1000&auto=format&fit=crop',
        altText: 'Back View & Puff Print Detail',
      },
      {
        url: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=1000&auto=format&fit=crop',
        altText: 'Fabric & Neckribbing Close-up',
      },
    ],
    variants: [
      {
        id: 'var-1-s',
        title: 'S / Washed Charcoal',
        availableForSale: true,
        selectedOptions: [{ name: 'Size', value: 'S' }, { name: 'Color', value: 'Washed Charcoal' }],
        price: { amount: '34.00', currencyCode: 'USD' },
        compareAtPrice: { amount: '48.00', currencyCode: 'USD' },
        sku: 'SNT-TEE-CHR-S',
      },
      {
        id: 'var-1-m',
        title: 'M / Washed Charcoal',
        availableForSale: true,
        selectedOptions: [{ name: 'Size', value: 'M' }, { name: 'Color', value: 'Washed Charcoal' }],
        price: { amount: '34.00', currencyCode: 'USD' },
        compareAtPrice: { amount: '48.00', currencyCode: 'USD' },
        sku: 'SNT-TEE-CHR-M',
      },
      {
        id: 'var-1-l',
        title: 'L / Washed Charcoal',
        availableForSale: true,
        selectedOptions: [{ name: 'Size', value: 'L' }, { name: 'Color', value: 'Washed Charcoal' }],
        price: { amount: '34.00', currencyCode: 'USD' },
        compareAtPrice: { amount: '48.00', currencyCode: 'USD' },
        sku: 'SNT-TEE-CHR-L',
      },
      {
        id: 'var-1-xl',
        title: 'XL / Washed Charcoal',
        availableForSale: true,
        selectedOptions: [{ name: 'Size', value: 'XL' }, { name: 'Color', value: 'Washed Charcoal' }],
        price: { amount: '34.00', currencyCode: 'USD' },
        compareAtPrice: { amount: '48.00', currencyCode: 'USD' },
        sku: 'SNT-TEE-CHR-XL',
      },
    ],
    seo: { title: 'Cyber Tokio Acid-Wash Oversized Tee | SNITCH', description: 'Drop shoulder streetwear graphic tee.' },
    tags: ['oversized-tees', 'featured', 'bestseller', 'hot-drop', 'apparel'],
    updatedAt: new Date().toISOString(),
    vendor: 'SNITCH Streetwear',
    category: 'oversized-tees',
    rating: 4.9,
    reviewsCount: 342,
  },
  {
    id: 'prod-snitch-2',
    handle: 'cuban-resort-linen-shirt',
    availableForSale: true,
    title: 'Havana Cuban Camp-Collar Linen Shirt',
    description: 'Relaxed resort Cuban shirt woven from lightweight breathable linen-cotton blend. Features custom wooden buttons and open camp collar.',
    descriptionHtml: '<p>Relaxed resort Cuban shirt woven from lightweight breathable linen-cotton blend. Features custom wooden buttons and open camp collar.</p>',
    options: [
      { id: 'opt-size-2', name: 'Size', values: ['S', 'M', 'L', 'XL'] },
      { id: 'opt-color-2', name: 'Color', values: ['Sand Beige', 'Sage Green', 'Midnight Ink'] },
    ],
    priceRange: {
      minVariantPrice: { amount: '42.00', currencyCode: 'USD' },
      maxVariantPrice: { amount: '42.00', currencyCode: 'USD' },
    },
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1000&auto=format&fit=crop',
      altText: 'Havana Cuban Camp-Collar Linen Shirt',
      width: 1000,
      height: 1000,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1000&auto=format&fit=crop',
        altText: 'Front View',
      },
      {
        url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1000&auto=format&fit=crop',
        altText: 'Lifestyle Shot',
      },
    ],
    variants: [
      {
        id: 'var-2-m',
        title: 'M / Sand Beige',
        availableForSale: true,
        selectedOptions: [{ name: 'Size', value: 'M' }, { name: 'Color', value: 'Sand Beige' }],
        price: { amount: '42.00', currencyCode: 'USD' },
        compareAtPrice: { amount: '58.00', currencyCode: 'USD' },
        sku: 'SNT-SHT-BEI-M',
      },
      {
        id: 'var-2-l',
        title: 'L / Sand Beige',
        availableForSale: true,
        selectedOptions: [{ name: 'Size', value: 'L' }, { name: 'Color', value: 'Sand Beige' }],
        price: { amount: '42.00', currencyCode: 'USD' },
        compareAtPrice: { amount: '58.00', currencyCode: 'USD' },
        sku: 'SNT-SHT-BEI-L',
      },
    ],
    seo: { title: 'Havana Cuban Camp-Collar Linen Shirt | SNITCH', description: 'Relaxed resort Cuban shirt.' },
    tags: ['korean-fit-shirts', 'featured', 'bestseller', 'apparel'],
    updatedAt: new Date().toISOString(),
    vendor: 'SNITCH Streetwear',
    category: 'korean-fit-shirts',
    rating: 4.8,
    reviewsCount: 189,
  },
  {
    id: 'prod-snitch-3',
    handle: 'tactical-parachute-cargos',
    availableForSale: true,
    title: 'Matrix Tactical Parachute Cargo Pants',
    description: 'Baggy high-street parachute cargo trousers with 6 utility pockets, ankle drawstrings, and articulated knee darts for effortless urban volume.',
    descriptionHtml: '<p>Baggy high-street parachute cargo trousers with 6 utility pockets, ankle drawstrings, and articulated knee darts.</p>',
    options: [
      { id: 'opt-size-3', name: 'Size', values: ['S', 'M', 'L', 'XL'] },
      { id: 'opt-color-3', name: 'Color', values: ['Stealth Olive', 'Pitch Black', 'Asphalt Grey'] },
    ],
    priceRange: {
      minVariantPrice: { amount: '58.00', currencyCode: 'USD' },
      maxVariantPrice: { amount: '58.00', currencyCode: 'USD' },
    },
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1000&auto=format&fit=crop',
      altText: 'Matrix Tactical Parachute Cargo Pants',
      width: 1000,
      height: 1000,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1000&auto=format&fit=crop',
        altText: 'Parachute Cargos Front',
      },
      {
        url: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?q=80&w=1000&auto=format&fit=crop',
        altText: 'Pocket Detailing',
      },
    ],
    variants: [
      {
        id: 'var-3-m',
        title: 'M / Stealth Olive',
        availableForSale: true,
        selectedOptions: [{ name: 'Size', value: 'M' }, { name: 'Color', value: 'Stealth Olive' }],
        price: { amount: '58.00', currencyCode: 'USD' },
        compareAtPrice: { amount: '78.00', currencyCode: 'USD' },
        sku: 'SNT-CRG-OLV-M',
      },
      {
        id: 'var-3-l',
        title: 'L / Stealth Olive',
        availableForSale: true,
        selectedOptions: [{ name: 'Size', value: 'L' }, { name: 'Color', value: 'Stealth Olive' }],
        price: { amount: '58.00', currencyCode: 'USD' },
        compareAtPrice: { amount: '78.00', currencyCode: 'USD' },
        sku: 'SNT-CRG-OLV-L',
      },
    ],
    seo: { title: 'Matrix Tactical Parachute Cargo Pants | SNITCH', description: 'Baggy utility parachute cargos.' },
    tags: ['parachute-cargos', 'featured', 'bestseller', 'hot-drop', 'apparel'],
    updatedAt: new Date().toISOString(),
    vendor: 'SNITCH Streetwear',
    category: 'parachute-cargos',
    rating: 4.95,
    reviewsCount: 412,
  },
  {
    id: 'prod-snitch-4',
    handle: 'monochrome-waffle-coord-set',
    availableForSale: true,
    title: 'Monochrome Waffle Resort Co-Ord Set',
    description: 'Matching 2-piece heavyweight textured waffle shirt and drawstring shorts set. High drape, ultra soft touch, perfect for vacation or weekend hangouts.',
    descriptionHtml: '<p>Matching 2-piece heavyweight textured waffle shirt and drawstring shorts set.</p>',
    options: [
      { id: 'opt-size-4', name: 'Size', values: ['S', 'M', 'L', 'XL'] },
      { id: 'opt-color-4', name: 'Color', values: ['Oatmeal Cream', 'Obsidian Black'] },
    ],
    priceRange: {
      minVariantPrice: { amount: '69.00', currencyCode: 'USD' },
      maxVariantPrice: { amount: '69.00', currencyCode: 'USD' },
    },
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
      altText: 'Monochrome Waffle Resort Co-Ord Set',
      width: 1000,
      height: 1000,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
        altText: 'Full Co-ord Fit',
      },
    ],
    variants: [
      {
        id: 'var-4-m',
        title: 'M / Oatmeal Cream',
        availableForSale: true,
        selectedOptions: [{ name: 'Size', value: 'M' }, { name: 'Color', value: 'Oatmeal Cream' }],
        price: { amount: '69.00', currencyCode: 'USD' },
        compareAtPrice: { amount: '95.00', currencyCode: 'USD' },
        sku: 'SNT-CRD-CRM-M',
      },
    ],
    seo: { title: 'Monochrome Waffle Resort Co-Ord Set | SNITCH', description: 'Matching textured waffle shirt and shorts set.' },
    tags: ['matching-coords', 'featured', 'new-arrival', 'apparel'],
    updatedAt: new Date().toISOString(),
    vendor: 'SNITCH Streetwear',
    category: 'matching-coords',
    rating: 4.85,
    reviewsCount: 120,
  },
  {
    id: 'prod-snitch-5',
    handle: 'varsity-leather-patch-bomber',
    availableForSale: true,
    title: 'Heritage Varsity Chenille Patch Bomber',
    description: 'Heavyweight wool-blend varsity jacket with vegan leather sleeves, custom chenille toweling patches, and retro striped ribbed hems.',
    descriptionHtml: '<p>Heavyweight wool-blend varsity jacket with vegan leather sleeves and custom chenille patches.</p>',
    options: [
      { id: 'opt-size-5', name: 'Size', values: ['M', 'L', 'XL'] },
      { id: 'opt-color-5', name: 'Color', values: ['Forest & Cream', 'Midnight & Slate'] },
    ],
    priceRange: {
      minVariantPrice: { amount: '98.00', currencyCode: 'USD' },
      maxVariantPrice: { amount: '98.00', currencyCode: 'USD' },
    },
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1000&auto=format&fit=crop',
      altText: 'Heritage Varsity Chenille Patch Bomber',
      width: 1000,
      height: 1000,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1000&auto=format&fit=crop',
        altText: 'Varsity Jacket View',
      },
    ],
    variants: [
      {
        id: 'var-5-l',
        title: 'L / Forest & Cream',
        availableForSale: true,
        selectedOptions: [{ name: 'Size', value: 'L' }, { name: 'Color', value: 'Forest & Cream' }],
        price: { amount: '98.00', currencyCode: 'USD' },
        compareAtPrice: { amount: '140.00', currencyCode: 'USD' },
        sku: 'SNT-JAC-VAR-L',
      },
    ],
    seo: { title: 'Heritage Varsity Chenille Patch Bomber | SNITCH', description: 'Retro varsity streetwear bomber.' },
    tags: ['varsity-jackets', 'featured', 'hot-drop', 'apparel'],
    updatedAt: new Date().toISOString(),
    vendor: 'SNITCH Outerwear',
    category: 'varsity-jackets',
    rating: 4.9,
    reviewsCount: 204,
  },
  {
    id: 'prod-snitch-6',
    handle: 'chunky-phantom-low-kicks',
    availableForSale: true,
    title: 'Phantom Retro Chunky Low Sneakers',
    description: 'Sculpted stacked EVA outsole paired with multi-layer tumbled leather and suede paneling. Soft mesh collar lining for continuous high-impact comfort.',
    descriptionHtml: '<p>Sculpted stacked EVA outsole paired with multi-layer tumbled leather and suede paneling.</p>',
    options: [
      { id: 'opt-size-6', name: 'Size', values: ['US 8', 'US 9', 'US 10', 'US 11'] },
      { id: 'opt-color-6', name: 'Color', values: ['Chalk & Crimson', 'Triple Black'] },
    ],
    priceRange: {
      minVariantPrice: { amount: '85.00', currencyCode: 'USD' },
      maxVariantPrice: { amount: '85.00', currencyCode: 'USD' },
    },
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop',
      altText: 'Phantom Retro Chunky Low Sneakers',
      width: 1000,
      height: 1000,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop',
        altText: 'Sneaker Side Profile',
      },
      {
        url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop',
        altText: 'Sole & Accent View',
      },
    ],
    variants: [
      {
        id: 'var-6-10',
        title: 'US 10 / Chalk & Crimson',
        availableForSale: true,
        selectedOptions: [{ name: 'Size', value: 'US 10' }, { name: 'Color', value: 'Chalk & Crimson' }],
        price: { amount: '85.00', currencyCode: 'USD' },
        compareAtPrice: { amount: '115.00', currencyCode: 'USD' },
        sku: 'SNT-SNK-WHT-10',
      },
    ],
    seo: { title: 'Phantom Retro Chunky Low Sneakers | SNITCH', description: 'Sculpted chunky low sneakers.' },
    tags: ['urban-footwear', 'featured', 'bestseller', 'footwear'],
    updatedAt: new Date().toISOString(),
    vendor: 'SNITCH Kicks',
    category: 'urban-footwear',
    rating: 4.88,
    reviewsCount: 310,
  },
  {
    id: 'prod-snitch-7',
    handle: 'vintage-satin-camp-shirt',
    availableForSale: true,
    title: 'Tokyo Satin Fluid Camp Shirt',
    description: 'High-lustre fluid satin short sleeve shirt with understated luxury sheen. Engineered with relaxed drop shoulders and Cuban collar for evening statements.',
    descriptionHtml: '<p>High-lustre fluid satin short sleeve shirt with understated luxury sheen.</p>',
    options: [
      { id: 'opt-size-7', name: 'Size', values: ['S', 'M', 'L', 'XL'] },
      { id: 'opt-color-7', name: 'Color', values: ['Emerald Green', 'Liquid Bronze', 'Charcoal Onyx'] },
    ],
    priceRange: {
      minVariantPrice: { amount: '46.00', currencyCode: 'USD' },
      maxVariantPrice: { amount: '46.00', currencyCode: 'USD' },
    },
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1000&auto=format&fit=crop',
      altText: 'Tokyo Satin Fluid Camp Shirt',
      width: 1000,
      height: 1000,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1000&auto=format&fit=crop',
        altText: 'Satin Shirt View',
      },
    ],
    variants: [
      {
        id: 'var-7-m',
        title: 'M / Emerald Green',
        availableForSale: true,
        selectedOptions: [{ name: 'Size', value: 'M' }, { name: 'Color', value: 'Emerald Green' }],
        price: { amount: '46.00', currencyCode: 'USD' },
        compareAtPrice: { amount: '62.00', currencyCode: 'USD' },
        sku: 'SNT-STN-GRN-M',
      },
    ],
    seo: { title: 'Tokyo Satin Fluid Camp Shirt | SNITCH', description: 'High lustre satin camp collar party shirt.' },
    tags: ['korean-fit-shirts', 'new-arrival', 'apparel'],
    updatedAt: new Date().toISOString(),
    vendor: 'SNITCH Streetwear',
    category: 'korean-fit-shirts',
    rating: 4.75,
    reviewsCount: 88,
  },
  {
    id: 'prod-snitch-8',
    handle: 'heavyweight-450-gsm-boxy-hoodie',
    availableForSale: true,
    title: 'Architect 450 GSM Heavyweight Boxy Hoodie',
    description: 'Pre-shrunk 450 GSM combed cotton fleece hoodie. Zero drawstring double layer hood, wide ribbing, and structured boxy profile.',
    descriptionHtml: '<p>Pre-shrunk 450 GSM combed cotton fleece hoodie with double layer hood.</p>',
    options: [
      { id: 'opt-size-8', name: 'Size', values: ['S', 'M', 'L', 'XL', 'XXL'] },
      { id: 'opt-color-8', name: 'Color', values: ['Bone Cream', 'Washed Slate', 'Pitch Black'] },
    ],
    priceRange: {
      minVariantPrice: { amount: '64.00', currencyCode: 'USD' },
      maxVariantPrice: { amount: '64.00', currencyCode: 'USD' },
    },
    featuredImage: {
      url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop',
      altText: 'Architect 450 GSM Heavyweight Boxy Hoodie',
      width: 1000,
      height: 1000,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop',
        altText: 'Hoodie Model Shot',
      },
    ],
    variants: [
      {
        id: 'var-8-l',
        title: 'L / Bone Cream',
        availableForSale: true,
        selectedOptions: [{ name: 'Size', value: 'L' }, { name: 'Color', value: 'Bone Cream' }],
        price: { amount: '64.00', currencyCode: 'USD' },
        compareAtPrice: { amount: '85.00', currencyCode: 'USD' },
        sku: 'SNT-HOD-BON-L',
      },
    ],
    seo: { title: 'Architect 450 GSM Heavyweight Boxy Hoodie | SNITCH', description: '450 GSM heavy organic cotton hoodie.' },
    tags: ['oversized-tees', 'bestseller', 'apparel'],
    updatedAt: new Date().toISOString(),
    vendor: 'SNITCH Streetwear',
    category: 'oversized-tees',
    rating: 4.92,
    reviewsCount: 265,
  },
];

export const MOCK_CART: Cart = {
  id: 'mock-cart-snitch',
  checkoutUrl: '#checkout-demo',
  subtotalAmount: { amount: '92.00', currencyCode: 'USD' },
  totalAmount: { amount: '99.36', currencyCode: 'USD' },
  totalTax: { amount: '7.36', currencyCode: 'USD' },
  totalQuantity: 2,
  lines: [
    {
      id: 'cart-line-1',
      quantity: 1,
      cost: { totalAmount: { amount: '34.00', currencyCode: 'USD' } },
      merchandise: {
        id: 'var-1-l',
        title: 'L / Washed Charcoal',
        selectedOptions: [
          { name: 'Size', value: 'L' },
          { name: 'Color', value: 'Washed Charcoal' },
        ],
        price: { amount: '34.00', currencyCode: 'USD' },
        image: {
          url: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1000&auto=format&fit=crop',
          altText: 'Cyber Tokio Acid-Wash Oversized Tee',
        },
        product: MOCK_PRODUCTS[0],
      },
    },
    {
      id: 'cart-line-2',
      quantity: 1,
      cost: { totalAmount: { amount: '58.00', currencyCode: 'USD' } },
      merchandise: {
        id: 'var-3-m',
        title: 'M / Stealth Olive',
        selectedOptions: [
          { name: 'Size', value: 'M' },
          { name: 'Color', value: 'Stealth Olive' },
        ],
        price: { amount: '58.00', currencyCode: 'USD' },
        image: {
          url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1000&auto=format&fit=crop',
          altText: 'Matrix Tactical Parachute Cargo Pants',
        },
        product: MOCK_PRODUCTS[2],
      },
    },
  ],
};
